### PR TITLE
Use curseForge API instead of JSON and refactored code

### PR DESCRIPTION
**Pull request by LeoCaprile**
Hey guys !
Really awesome iniciative and project, I'm looking forward to contribute, I see you guys are using a plain JSON, that is not really scalable to be honest, instead we can use directly the API of curse forge, to have updated data about the mods.

This PR is missing filtering, but I wanted to share with you guys, so you can test it on your machine.

### CODE REVIEW

**Comment by JavaBoii** [comment]
hahaha told ya @yehorscode. Good work @LeoCaprile.

**Comment by JavaBoii** [comment]
Also @LeoCaprile we have a discord for discussing changes etc.
https://discord.gg/93ngTSM9

**Comment by yehorscode** [comment]
Okay, i haven't tested It, but i think for Modrinth we should keep a json file, for curseforge pulling data on each load would not be bad. I don't want to request too much to Modrinth because
1. They have a request limit
2. I don't really want to overload Modrinth servers (i love Modrinth)

**Comment by LeoCaprile** [comment]
> Okay, i haven't tested It, but i think for Modrinth we should keep a json file, for curseforge pulling data on each load would not be bad. I don't want to request too much to Modrinth because
> 
> 1. They have a request limit
> 2. I don't really want to overload Modrinth servers (i love Modrinth)

You're right for modrinth, it's like 300 request per minute, and I think that's not gonna be enough if we have like a lot of traffic on the web. We could make an API, that runs a cron job that get that info each minute.

**Comment by yehorscode** [comment]
I mean, to get all the addons from Modrinth It takes 3 requests. And from Curseforge around 3 or 4 i think (or 5?). Merging same addons would be easier in a json file (by name) and site will load faster

**Pull request merged**
